### PR TITLE
chore: Use homebrew podman instead of running in a container

### PR DESCRIPTION
**Pull request by gmpinder**

### CODE REVIEW

**Review by fiftydinar — APPROVED** [review]

**Comment by gmpinder** [comment]
It's looking like it's working https://github.com/gmpinder/testos/actions/runs/9037735076/job/24838169814

**Comment by xynydev** [comment]
Did you test if this makes the build faster over a container?

**Comment by gmpinder** [comment]
> Did you test if this makes the build faster over a container?

I'm running into some issues with it at the moment so I don't think it will be.

**Comment by xynydev** [comment]
If it doesn't seem helpful, you don't have to work on it, and we can just close the PR for now.

**Comment by gmpinder** [comment]
> If it doesn't seem helpful, you don't have to work on it, and we can just close the PR for now.

Yeah not too helpful especially cause it takes upwards of 3 minutes just to install podman.

**Pull request closed without merging**
